POST http://localhost:4000/api/respuestas/nuevasRespuestas
Content-Type: application/json

{
  "usuario_id": 1,
  "respuestas": [
    {
      "pregunta_id": 15,
      "respuesta": "Me siento bien con mi carga laboral"
    },
    {
      "pregunta_id": 16,
      "respuesta": "Sí, he experimentado estrés"
    },
    {
      "pregunta_id": 17,
      "respuesta": "Dolor de cabeza, fatiga, insomnio"
    }
  ]
}
